-- Eliminar tablas en orden correcto (primero las dependientes)
drop table if exists "ReservaDetalle";
drop table if exists "Producto";
drop table if exists "Reserva";
drop table if exists "Huesped";
drop table if exists "Cuarto";
drop table if exists "Piso";

drop type if exists "caracteristica_tipo";
drop type if exists "estados";
drop type if exists "estado_reserva";

-- TIPOS ENUM
CREATE TYPE "caracteristica_tipo" AS ENUM (
  'tv',
  'wifi',
  'aire_acondicionado',
  'baño_privado',
  'jacuzzi'
);

CREATE TYPE "estados" AS ENUM ('disponible', 'ocupado');

CREATE TYPE "estado_reserva" AS ENUM ('en_curso', 'finalizado');

-- TABLAS BASE
CREATE TABLE "Piso" (
  "id_piso" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numero" int
);

CREATE TABLE "Cuarto" (
  "id_cuarto" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numero" int,
  "piso_id" bigint,
  "caracteristicas" caracteristica_tipo[],
  "estados" estados default 'disponible' not null,
  "precio_por_noche" decimal
);

CREATE TABLE "Huesped" (
  "id_huesped" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "dni" varchar
);

CREATE TABLE "Reserva" (
  "id_reserva" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "huesped_id" bigint,
  "cuarto_id" bigint,
  "fecha_entrada" date,
  "fecha_salida" date,
  "total" decimal,
  "estado" estado_reserva default 'en_curso' not null
);

-- PRODUCTOS (catálogo)
CREATE TABLE "Producto" (
  "id_producto" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar not null,
  "precio_unitario" decimal not null,
  "descripcion" text,
  "activo" boolean default true not null
);

-- DETALLE DE RESERVA (relación N productos por cada reserva)
CREATE TABLE "ReservaDetalle" (
  "id_detalle" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reserva_id" bigint not null,
  "producto_id" bigint not null,
  "cantidad" int not null default 1,
  "precio_unitario" decimal not null,
  "subtotal" decimal not null
);

-- RELACIONES
ALTER TABLE "Cuarto"
  ADD FOREIGN KEY ("piso_id") REFERENCES "Piso" ("id_piso");

ALTER TABLE "Reserva"
  ADD FOREIGN KEY ("huesped_id") REFERENCES "Huesped" ("id_huesped");

ALTER TABLE "Reserva"
  ADD FOREIGN KEY ("cuarto_id") REFERENCES "Cuarto" ("id_cuarto");

ALTER TABLE "ReservaDetalle"
  ADD FOREIGN KEY ("reserva_id") REFERENCES "Reserva" ("id_reserva");

ALTER TABLE "ReservaDetalle"
  ADD FOREIGN KEY ("producto_id") REFERENCES "Producto" ("id_producto");
