drop table if exists Piso;
drop table if exists Cuarto;
drop table if exists Huesped;
drop table if exists Reserva;
drop type if exists caracteristica_tipo;
drop type if exists estados;


CREATE TYPE "caracteristica_tipo" AS ENUM (
  'tv',
  'wifi',
  'aire_acondicionado',
  'baño_privado',
  'jacuzzi'
);

CREATE TYPE estados AS ENUM ('disponible', 'ocupado');

CREATE TABLE "Piso" (
  "id_piso" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numero" int
);

CREATE TABLE "Cuarto" (
  "id_cuarto" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numero" int,
  "piso_id" bigint,
  "caracteristicas" caracteristica_tipo[],
  "estados" estados default 'disponible' not null,
  "precio_por_noche" decimal
);

CREATE TABLE "Huesped" (
  "id_huesped" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "dni" varchar
);

CREATE TABLE "Reserva" (
  "id_reserva" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "huesped_id" bigint,
  "cuarto_id" bigint,
  "fecha_entrada" date,
  "fecha_salida" date,
  "total" decimal
);

ALTER TABLE "Cuarto" ADD FOREIGN KEY ("piso_id") REFERENCES "Piso" ("id_piso");

ALTER TABLE "Reserva" ADD FOREIGN KEY ("huesped_id") REFERENCES "Huesped" ("id_huesped");

ALTER TABLE "Reserva" ADD FOREIGN KEY ("cuarto_id") REFERENCES "Cuarto" ("id_cuarto");
